language: node_js

node_js:
- 10

cache:
  directories:
    - $HOME/.npm

script:
  - npm test

notifications:
  email: false

before_deploy:
  - npm run build:demo

deploy:
  local_dir: demo/build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
